export enum MedicalSpecialty {
  ALERGOLOGIA = "Allergology",
  ANESTESIOLOGIA = "Anesthesiology",
  ANGIOLOGIA = "Angiology",
  CANCEROLOGIA = "Oncology",
  CARDIOLOGIA = "Cardiology",
  CIRURGIA_CARDIOVASCULAR = "Cardiovascular Surgery",
  CIRURGIA_CABECA_PESCOCO = "Head and Neck Surgery",
  CIRURGIA_DIGESTIVA = "Digestive Surgery",
  CIRURGIA_GERAL = "General Surgery",
  CIRURGIA_PEDIATRICA = "Pediatric Surgery",
  CIRURGIA_PLASTICA = "Plastic Surgery",
  CIRURGIA_TORACICA = "Thoracic Surgery",
  CIRURGIA_VASCULAR = "Vascular Surgery",
  CLINICA_MEDICA = "Internal Medicine",
  DERMATOLOGIA = "Dermatology",
  ENDOCRINOLOGIA = "Endocrinology",
  ENDOSCOPIA = "Endoscopy",
  GASTROENTEROLOGIA = "Gastroenterology",
  GERIATRIA = "Geriatrics",
  GINECOLOGIA_OBSTETRICIA = "Gynecology & Obstetrics",
  HEMATOLOGIA = "Hematology",
  HEPATOLOGIA = "Hepatology",
  HOMEOPATIA = "Homeopathy",
  INFECTOLOGIA = "Infectious Disease",
  MASTOLOGIA = "Breast Surgery",
  MEDICINA_DE_EMERGENCIA = "Emergency Medicine",
  MEDICINA_DO_ESPORTO = "Sports Medicine",
  MEDICINA_DO_TRABALHO = "Occupational Medicine",
  MEDICINA_DE_FAMILIA = "Family Medicine",
  MEDICINA_FISICA_REABILITACAO = "Physical Medicine & Rehabilitation",
  MEDICINA_INTENSIVA = "Intensive Care",
  MEDICINA_LEGAL = "Forensic Medicine",
  NEFROLOGIA = "Nephrology",
  NEUROCIRURGIA = "Neurosurgery",
  NEUROLOGIA = "Neurology",
  NUTROLOGIA = "Nutrition Medicine",
  OFTALMOLOGIA = "Ophthalmology",
  ONCOLOGIA_CLINICA = "Clinical Oncology",
  ORTOPEDIA_TRAUMATOLOGIA = "Orthopedics",
  OTORRINOLARINGOLOGIA = "Otolaryngology (ENT)",
  PATOLOGIA = "Pathology",
  PATOLOGIA_CLINICA = "Clinical Pathology",
  PEDIATRIA = "Pediatrics",
  PNEUMOLOGIA = "Pulmonology",
  PSIQUIATRIA = "Psychiatry",
  RADIOLOGIA = "Radiology",
  RADIOTERAPIA = "Radiation Therapy",
  REUMATOLOGIA = "Rheumatology",
  UROLOGIA = "Urology",
}

export const medicalSpecialties = Object.entries(MedicalSpecialty).map(
  ([key, value]) => ({
    value: MedicalSpecialty[key as keyof typeof MedicalSpecialty],
    label: value,
  }),
);
